# Generated by Django 4.1.1 on 2022-10-16 08:32
'''to apply migration use (py manage.py makemigrations)--> note: use it if migration already applies to the project
   then (py manage.py migrate)'''
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='portfolio/images/')),
                ('url', models.URLField()),
            ],
        ),
    ]
